### ISSUE TITLE
Raw text format

### ISSUE THREAD

**Issue by LoopControl** [taprosoft/llm_finetuning#4]
Is it possible to do raw-text training (not instruction style - just feeding full text of literature)?

If so could you suggest a template to do this?

**Comment by taprosoft** [comment]
@LoopControl Raw text format is simple enough, just need to chunk it into smaller parts that can fit into the model context size. Right now the prompt template assume that you already separate the text into small sample which can feed to the model one-by-one. I am working on a simple chunking feature so you can feed a big text file as the training data. Stay tuned.

**Comment by taprosoft** [comment]
@LoopControl training with raw text file has been added in https://github.com/taprosoft/llm_finetuning/commit/5cf16e9b24f3cc84af794269447daec5211ee65e. Use `--prompt_template text --data_path path/to/text/file` to start the fine-tuning.
