### ISSUE TITLE
Sharegpt format error

### ISSUE THREAD

**Issue by Ktrcoyote** [taprosoft/llm_finetuning#5]
I formatted my data as shareGPT but it keeps throwing up this error. 

> Failed to read file '/workspace/llm_finetuning/datasets/dataset.json' with error <class 'pyarrow.lib.ArrowInvalid'>: Could not convert 'USER' with type str: tried to convert to int64
Traceback (most recent call last):                      
  File "/usr/local/lib/python3.10/dist-packages/datasets/builder.py", line 1879, in _prepare_split_single
    for _, table in generator:
  File "/usr/local/lib/python3.10/dist-packages/datasets/packaged_modules/json/json.py", line 156, in _generate_tables
    raise ValueError(f"Not able to read records in the JSON file at {file}.") from None
ValueError: Not able to read records in the JSON file at /workspace/llm_finetuning/datasets/dataset.json.

**Comment by LoopControl** [comment]
Paste a small portion of the data so we can see where the issue is.

**Comment by Ktrcoyote** [comment]
I'm trying to clone myself through a decades worth of texts. It's all formatted in sharegpt format. Admittedly the "id" value is made up I was just hoping that would fix the problem. It didn't. I've run it through several JSON validators and receive no issue

````
[
    {
        "id": "O3e7E0nT",
        "conversations": [
            {
                "from": "USER",
                "value": "I checked the purse It's a good purse"
            },
            {
                "from": "ASSISTANT",
                "value": "Cool. I hope she likes it Thanks for checking"
            }
        ]
    },

**Comment by Ktrcoyote** [comment]
Just an update. I tried Text-Generation-Webui and hit the same problem so at least it's not specific to your work.

**Comment by taprosoft** [comment]
@Ktrcoyote Make sure that you wrapped the conversation list in "conversation" field such as this example:
```json
{"conversations": [
  {"from": "human", "value": "hi"},
  {"from": "gpt", "value": "hi"},
  {"from": "human", "value": "how are you"},
  {"from": "gpt", "value": "good"}
]}
```
(from https://github.com/taprosoft/llm_finetuning/blob/main/templates/README.md)

**Comment by taprosoft** [comment]
@Ktrcoyote I don't encounter any problem training with the similar data format as yours. You can check my example here:
https://pastebin.com/5nqHwbv0
